development:
  adapter: postgresql
  database: slff-bend-postgresql-database
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  datslff-bend-postgresql-database
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database:slff-bend-postgresql-database
  pool: 5
  timeout: 5000

# development:
#   adapter: postgresql
#   encoding: unicode
#   database: myapp_development
#   pool: 5
#   username: brenden
#   password:
#   timeout: 5000
 
# test:
#   adapter: postgresql
#   encoding: unicode
#   database: myapp_test
#   pool: 5
#   username: brenden
#   password:
#   timeout: 5000